#!/bin/bash
export TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL="1"
export FLASH_ATTENTION_TRITON_AMD_ENABLE="TRUE"
export PYTORCH_TUNABLEOP_ENABLED="1"
export PYTORCH_TUNABLEOP_TUNING_DURATION="short"
export PYTORCH_ALLOC_CONF="expandable_segments:True"
export MIOPEN_DEBUG_CONV_GEMM=1
export MIOPEN_FIND_MODE=2
export PYTHONPATH="$(pwd)/codeclm/tokenizer/Flow1dVAE:$PYTHONPATH"
